Add jrePath option
libgdx/packr pull request #195
Opened 2021-02-15 21:20 UTC by petoncle

This PR implements a new field called jrePath in config.json.
This is my solution to the problem described here: https://github.com/libgdx/packr/issues/191
The main idea is to let the user choose the name of the bundled JRE folder so that a self-updating app can easily switch to a new JRE.
Let me know if this solution is not appropriate and/or if there are better alternatives.

I've also added the --jrePath option to the packaging tool (not the launcher).
The default value is "jre" for backward compatibility.
I've changed the tests to use this new option: "--jrePath jre-123456". The tests are successful on Windows, Linux and Mac.

Anyway this is mostly a proof of concept, I'm trying to get a discussion going about it.

By the way @karlsabo I'm not sure how you build, run the tests and publish launcher natives and packr-all. Are you able to do it in a single step or are there multiple steps involved?
To do it in one single step in my fork I had to make a custom GitHub Actions workflow that 1- publishes the packr launcher native executables to GitHub Packages, and 2- runs the tests.

2021-02-16 03:39 UTC, karlsabo requested changes
Thanks so much for the PR! I made a few comments I would like to see changed. The biggest one being the parameter type to loadJNIFunctions.

2021-02-16 03:39 UTC, karlsabo commented on PackrLauncher/src/main/cpp/win32/packr_win32.cpp
> +void loadLibraries(const TCHAR* libraryPattern) {
What's the reason for changing from the typedef PTCHAR?

2021-02-16 03:39 UTC, karlsabo commented on PackrLauncher/src/main/headers/packr.h
> +	bool loadJNIFunctions(const std::string& jrePath, GetDefaultJavaVMInitArgs* getDefaultJavaVMInitArgs, CreateJavaVM* createJavaVM);
For consistency I would prefer const dropt_char* instead of string.

It would also feel less awkward with the Windows code assuming it's getting a string with UTF-8 encoded data in it.

2021-02-16 03:39 UTC, karlsabo commented on PackrLauncher/src/main/cpp/win32/packr_win32.cpp
> +const TCHAR* stringToTcharPointer(const std::string& s) {
We should use PTCHAR for consistency.

2021-02-16 03:39 UTC, karlsabo commented on PackrLauncher/src/main/cpp/packr.cpp
> +    if ('/' == trimmedJrePath.back())
I'm assuming a trailing '/' breaks one or more of the loadJNIFunctions implementations? We should also check for '\\' and remove that too, or make a comment if this only affects Linux or macOS.

2021-02-16 03:39 UTC, karlsabo commented on PackrAllTestApp/packrAllTestApp.gradle.kts
> +      args("jre-123456")
Thanks for updating the test! Could you add a Unicode character here so we know if it works or not on Windows? You could use Ä, like I do above `// Add the Ä to test unicode paths`

2021-02-16 03:39 UTC, karlsabo commented on PackrLauncher/src/main/cpp/win32/packr_win32.cpp
> +   std::replace(backslashedJrePath.begin(), backslashedJrePath.end(), '/', '\\');
I don't know for sure, but I could imagine a case where this method segfaults when it's passed a string that actually contains UTF-8 data. I would like this method to take a PTCHAR* (const dropt_char*), then we know what kind of data we're really dealing with.

2021-02-16 03:39 UTC, karlsabo commented on PackrLauncher/src/main/cpp/packr.cpp
> +        getJsonValue(jsonRoot, "jrePath").as_string() : "jre";
Great job handling the backwards compatibility case, it's easy to break these since there aren't any tests for them.

2021-02-16 03:43 UTC, karlsabo commented
Oh, please also update the changelog.md, add something like:

# Unreleased 3.1.0
1. Added an option to specify the JRE directory in the configuration file. 

Also update the readme.md with your new option and JSON config additions.

Add yourself to the AUTHORS file too (optional).

2021-02-16 03:57 UTC, karlsabo commented
Oh, and to answer your question about building the packr-all JAR, yes, you have to run `gradlew PackrLauncher:publish` on every platform so the executable files are available. I use GitLab CI to do it all for me, you can look at `.gitlab-ci.yml` in the repository.

2021-02-16 11:52 UTC, petoncle commented on PackrLauncher/src/main/headers/packr.h
> +	bool loadJNIFunctions(const std::string& jrePath, GetDefaultJavaVMInitArgs* getDefaultJavaVMInitArgs, CreateJavaVM* createJavaVM);
Yeah you're right I should replace string with dropt_char*. But to do that I need to find a way to 1. remove potential trailing slash from a dropt_char* (needed in packr.cpp), and 2. concatenate two dropt_char* (needed in packr_win32.cpp and packr_linux.cpp).

2021-02-16 12:00 UTC, petoncle commented on PackrLauncher/src/main/cpp/packr.cpp
> +    if ('/' == trimmedJrePath.back())
It is assumed that the jrePath value (coming from config.json) only contains forward slashes `/`. I've mentioned that in the description of the --jrePath command line parameter.
Both Linux and Mac's loadJNIFunctions() work with `/`.
Windows's loadJNIFunctions() works with `\`, and that's why I replace all `/` with `\` in Windows's loadJNIFunctions().

(I guess we could accept `\` in config.json and replace them with `/` in packr.cpp launchJavaVM().)

Now to answer your question, a trailing `/` breaks Windows and Linux's loadJNIFunctions() because we do:
```c++
jrePath + "/lib/server/libjvm.so" // Linux.
jrePath + "\\bin" // Windows.
```
That's why I remove any trailing `/` in packr.cpp launchJavaVM().

2021-02-16 15:22 UTC, karlsabo commented on PackrLauncher/src/main/headers/packr.h
> +	bool loadJNIFunctions(const std::string& jrePath, GetDefaultJavaVMInitArgs* getDefaultJavaVMInitArgs, CreateJavaVM* createJavaVM);
1. There's an example of that in packr.cpp when calling `changeWorkingDir`, look at the `launchJavaVM` function.
2. See below, there are C string functions for this, will need to use the correct one on Windows.
3. There's similar code in packr.cpp see the top of the file for #ifdef UNICODE. Then look at: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strcat-wcscat-mbscat?view=msvc-160
   * ```cpp
     #ifdef UNICODE
     #include <codecvt>
     #define stringCompare wcscmp
     #define findLastCharacter wcsrchr
     #else
     #define stringCompare strcmp
     #define findLastCharacter strrchr
     #endif
     ```

2021-02-16 19:32 UTC, petoncle commented on PackrLauncher/src/main/cpp/win32/packr_win32.cpp
> +void loadLibraries(const TCHAR* libraryPattern) {
The reason for changing is that I would get the following error:
```
packr_win32.cpp(295): error C2664: 'void loadLibraries(const PTCHAR)': 
cannot convert argument 1 from 'const dropt_char *' to 'const PTCHAR'
```

2021-02-16 19:34 UTC, petoncle commented on PackrLauncher/src/main/headers/packr.h
> +	bool loadJNIFunctions(const std::string& jrePath, GetDefaultJavaVMInitArgs* getDefaultJavaVMInitArgs, CreateJavaVM* createJavaVM);
Thanks @karlsabo. I've made the changes to replace std::string with dropt_char*. Let me know if there if it looks fine.

2021-02-17 04:18 UTC, karlsabo requested changes
Code looks good, thanks for the PR.

Can you update the changelog and readme files?

2021-02-17 10:56 UTC, petoncle commented
While reviewing the README I realized that you can pass a JSON as input to the packr tool instead of using command line arguments. I was missing code to parse the new jrePath option from that JSON and so I've added it just now.

2021-02-18 15:35 UTC, karlsabo approved these changes
Thanks @petoncle!

2021-02-19 14:55 UTC, merged