Replace config.json with <app name>.json
libgdx/packr pull request #196
Opened 2021-02-21 13:14 UTC by petoncle

This PR changes the launchers. They now look for a config file named `<app name>.json`.
App name is the file name of the launcher. On Windows, the `.exe` suffix is removed.

The painful part was the management of unicode paths (again 😔). The tests have been updated to name the launcher `PackrAllTestAppÄ`, and the default configuration file is `PackrAllTestAppÄ.json`.

Linked to issue https://github.com/libgdx/packr/issues/174.

I'll wait for @karlsabo to give some feedback before updating the README.

2021-02-21 15:18 UTC, karlsabo requested changes
Thanks for another great PR!

Code looks good, I think there's a good opportunity for code reuse with the `getDefaultConfigurationPath` but it might not be worth the effort.

Other than that, make sure you update the README and changelog files too.

Thanks,
Karl

2021-02-21 15:18 UTC, karlsabo commented on PackrLauncher/src/main/cpp/packr.cpp
> +#ifdef UNICODE
Nice fix, thanks.

2021-02-21 15:18 UTC, karlsabo commented on PackrLauncher/src/main/cpp/win32/packr_win32.cpp
> +        wstring_convert<codecvt_utf8_utf16<wchar_t>> converter;
```suggestion
    wstring_convert<codecvt_utf8_utf16<wchar_t>> converter;
```

2021-02-21 15:18 UTC, karlsabo commented on PackrLauncher/src/main/cpp/win32/packr_win32.cpp
> +    bool hasExeSuffix = executableNameWstring.size() >= exeSuffix.size() &&
I don't mind this, but there is potential to make the code more generic if you used `find_last_of` to simply find the last `.` and then use that sub-string.

2021-02-21 15:18 UTC, karlsabo commented on PackrLauncher/src/main/cpp/win32/packr_win32.cpp
> +    bool hasExeSuffix = executableNameWstring.size() >= exeSuffix.size() &&
W/ dr opt typedefs and some `#ifdef` you might even be able to put this in packr.cpp instead of having to define it for every platform.

2021-02-21 16:16 UTC, petoncle commented on PackrLauncher/src/main/cpp/win32/packr_win32.cpp
> +    bool hasExeSuffix = executableNameWstring.size() >= exeSuffix.size() &&
Thanks for the feedback Karl! I wanted to only remove ".exe" for Windows but it's not worth it and I agree with you we can put `getDefaultConfigurationPath()` in packr.cpp instead. 
I've committed the changes for that.
I've also looked at `find_last_of` and it can't be used to look for a substring but just single characters so I kept using wstring instead. I wouldn't want to just look for "." to avoid stripping something other than ".exe". Let me know if there's a better solution.

2021-02-21 16:20 UTC, karlsabo commented on PackrLauncher/src/main/cpp/win32/packr_win32.cpp
> +    bool hasExeSuffix = executableNameWstring.size() >= exeSuffix.size() &&
I can't think of a better way.

2021-02-21 16:21 UTC, karlsabo requested changes
Code looks great, thanks. Just need to update the change log and read me files. Thanks so much for the PR.

2021-02-21 17:35 UTC, petoncle commented
Updated the README and CHANGELOG. Let me know if it's enough or if you would add more details about it.

2021-02-21 17:36 UTC, petoncle commented
Oh also I've put it under release 3.1.0, not sure if that's correct.

2021-02-21 22:05 UTC, karlsabo approved these changes
Looks good, I'll probably release as 4.0 but I can change that before I do the release.

Thanks for the PR!

2021-02-21 22:06 UTC, merged

2021-02-21 22:32 UTC, karlsabo commented
I pulled locally and my CI published your changes:
https://artifactory.nimblygames.com/artifactory/ng-public-snapshot/com/badlogicgames/packr/packr-all/3.1.0-SNAPSHOT/
packr-all-3.1.0-20210221.221700-10.jar           21-Feb-2021 22:17  3.47 MB

2021-02-27 18:53 UTC, petoncle commented
@karlsabo I found that it wasn't working when no arguments are passed to the launcher (`argc == 0`)! I must have been testing it with `-c` the whole time and completely missed that!
The fix is simple: https://github.com/petoncle/packr/commit/65158768dc9332f1d7db6f6cc018b5136234dfae (I also cleaned 2 log statements that were printing `executableName` - used for debugging during development and I forgot to remove it).